version: "3"

services:
  dynamodb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - crud-serverless-users:/home/dynamodblocal/db

volumes:
  crud-serverless-users:
    driver: local
